_format_version: "2.1"

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-routes
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors

  - name: rest
    url: http://rest:3000
    routes:
      - name: rest-routes
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors

  - name: realtime
    url: http://realtime:4000/socket
    routes:
      - name: realtime-routes
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors

  - name: storage
    url: http://storage:5000
    routes:
      - name: storage-routes
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - HEAD
        - PUT
        - PATCH
        - POST
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - apikey
        - x-client-info
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
